### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Aalok Singh 2",
    "email": "aalok2@zoho.com",
    "address": "124 main street",
    "dateOfBirth": "2002-09-09",
    "registeredDate": "2025-12-12"
}
###