### GET request to get all patients
GET  http://lb-2aafc01d.elb.localhost.localstack.cloud:4004/api/patients?page=1&sort=desc&size=2
Authorization: Bearer {{token}}
###



http://lb-2aafc01d.elb.localhost.localstack.cloud:22399